# backend-deployment.aml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: used2book-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: used2book-backend
  template:
    metadata:
      labels:
        app: used2book-backend
    spec:
      containers:
      - name: backend
        image: maryneza/used2book-backend:latest
        ports:
        - containerPort: 80
        env:
          - name: ENV
            value: "production"

          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
            
          - name: GOOGLE_CLIENT_ID
            value: "918559002661-5101usb99nesds25u7dmkirs88sq81nf.apps.googleusercontent.com"
          - name: GOOGLE_CLIENT_SECRET
            value: "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"

          - name: DB_HOST
            value: "mysql"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "used2book"
          - name: DB_PASSWORD
            value: "used2book_password"
          - name: DB_NAME
            value: "used2book_db"

          - name: JWT_ACCESS_TOKEN_SECRET
            value: "maryne_access_token_jwt"

          - name: JWT_REFRESH_TOKEN_SECRET
            value: "maryne_refresh_token_jwt"

          - name: IMAGEKIT_URL_ENDPOINT
            value: "https://ik.imagekit.io/used2bookID"
          - name: IMAGEKIT_PRIVATE_KEY
            value: "private_D6zjnAm1Xp+zjOXRYIWDzVxQZZ8="
          - name: IMAGEKIT_PUBLIC_KEY
            value: "public_8Cnh07qG7NuAK/t85iU/cZMaxco="

          - name: TWILIO_ACCOUNT_SID
            value: "ACcd1d2b7117b1c349ae70f3da1cc04d4b"
          - name: TWILIO_AUTH_TOKEN
            value: "b2c8701cc4a192d2c508e3fb2bd47e04"
          - name: TWILIO_PHONE_NUMBER
            value: "+16205539628"

          - name: GOOGLE_SHEET_ID
            value: "1L3aqd5xgSxZW-La5Xaf6U6xNDkoYj-Apyg1ZANAwqPU"
          - name: GOOGLE_SHEET_API_KEY
            value: "AIzaSyCohcWnzXOyvG8z815cgT-ktEbtfeo-4oo"

          - name: STRIPE_SECRET_KEY
            value: "sk_test_51QwT0ERuztYV4mOwchfI9UvVPxYniqs5eeOkvgaBrTtbclHD8gPDbE5ih3jqPahOKlyP8gyTwY61hWOarRJrScZ500uEE0MSot"

          - name: OMISE_PUBLIC_KEY
            value: "pkey_test_62x4s0hllpjgyz1pm91"

          - name: OMISE_SECRET_KEY
            value: "skey_test_62x4s0i3njlu0fstt2p"

                
